import type { Metadata } from 'next' 
import '@styles/Styler.scss'
import SideBar from '@/components/SideBar'
import TopBar from '@/components/TopBar'
 

export const metadata: Metadata = {
  title: 'Front End Test | Nathaniel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className='Layout'>
          <SideBar/>  
          <main>
            <TopBar />
            {children}
          </main>
        </div>      
      </body>
    </html>
  )
}
