import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'
import '@styles/Styler.scss'
import SideBar from '@/components/SideBar'

const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <div className='Layout'>
          <SideBar/>  
          {children}
        </div>      
      </body>
    </html>
  )
}
